In [1]:
import pandas as pd
import scipy.io as sc
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

lossaux = np.array(sc.loadmat('LOSS.mat')['LOSS'])
payaux = np.array(sc.loadmat('PAY.mat')['PAY'])

                  
loss = pd.DataFrame(lossaux)
loss.insert(len(loss.columns), 'Loss', 1)
pay = pd.DataFrame(payaux, index =range(969,4793))
pay.insert(len(pay.columns), 'Loss', 0)
columns = ['NOI','DSCR','LTV','Balance','Rate','Fee','Net Mortgage Rate','Year Built','Renovation','Occupancy','ZipPop','CR','CS','CS Ratio','NOI Ratio','PV Ratio','IR', 'Loss']
frame = [loss, pay]
dataset = pd.concat(frame)
dataset.columns = columns
dataset.head()

,NOI,DSCR,LTV,Balance,Rate,Fee,Net Mortgage Rate,Year Built,Renovation,Occupancy,ZipPop,CR,CS,CS Ratio,NOI Ratio,PV Ratio,IR,Loss
0,697399.0,1.35,69.4,7250000.0,5.25,0.0312,5.2188,1998.0,100.0,22919.0,7.663725,351.880464,1.136903,4.144921,0.143158,0.127688,5.0,1
1,1088638.0,1.36,61.3,9100000.0,5.52,0.0312,5.4888,1984.0,95.4,23129.0,8.779339,463.441807,1.502204,4.144921,0.310453,0.242793,21.0,1
2,618081.0,1.31,66.0,6650000.0,5.45,0.0312,5.4188,2001.0,87.2,32504.0,7.358107,293.888839,1.076208,4.419219,0.110992,0.101224,2.0,1
3,260695.0,1.55,64.2,2600000.0,5.21,0.1112,5.0988,1965.0,100.0,32376.0,7.781940,353.971808,3.315033,4.242222,0.117658,0.080235,40.0,1
4,607133.0,1.26,65.8,6500000.0,5.29,0.0312,5.2588,1970.0,100.0,12942.0,7.404061,316.183875,2.961139,4.242222,0.274014,0.196397,4.0,1

In [20]:
from sklearn import preprocessing
#print(preprocessing.StandardScaler(dataset))
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result
dataclean = pd.DataFrame(normalize(dataset))
dataclean.head()

,NOI,DSCR,LTV,Balance,Rate,Fee,Net Mortgage Rate,Year Built,Renovation,Occupancy,ZipPop,CR,CS,CS Ratio,NOI Ratio,PV Ratio,IR,Loss
0,0.020436,0.016397,0.815897,0.024381,0.229508,0.104874,0.555316,0.953368,1.000000,0.204197,0.525632,0.573800,0.571973,0.262580,0.015077,0.013145,0.047619,1.0
1,0.032584,0.016861,0.720670,0.030998,0.278689,0.104874,0.584045,0.880829,0.953535,0.206093,0.614106,0.661633,0.578654,0.262580,0.034106,0.026155,0.200000,1.0
2,0.017973,0.014541,0.775925,0.022234,0.265938,0.104874,0.576597,0.968912,0.870707,0.290712,0.501395,0.528142,0.570863,0.309777,0.011418,0.010153,0.019048,1.0
3,0.006876,0.025677,0.754764,0.007748,0.222222,0.373782,0.542547,0.782383,1.000000,0.289557,0.535007,0.575446,0.611808,0.279322,0.012176,0.007781,0.380952,1.0
4,0.017633,0.012221,0.773574,0.021698,0.236794,0.104874,0.559572,0.808290,1.000000,0.114144,0.505039,0.545695,0.605336,0.279322,0.029961,0.020911,0.038095,1.0