In [41]:
import os
import pandas as pd
import numpy as np
from sklearn import preprocessing,metrics 
from IPython.core.display import HTML
pd.set_option("display.max_columns",75)
import warnings
import math
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn import linear_model,svm
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve

In [5]:
df = pd.read_excel('JPM Disposed.xlsx', skiprows = 1)

In [6]:
df.head()

,Unnamed: 0,Property\nName,Trustee\nLoan ID,Secur\nLoan\nBalance,DSCR,LTV,Before Disposition\nBalance,Before Disposition\nPaid Thru\nDate,Before Disposition\nDefeased\nStatus,Before Disposition\nModified\nStatus,Before Disposition\nModification\nDate,Disposition\nDate,Disposition\nType,Disposition\nSub Type,Disposition\nComments,Loss\nAmount,Loss\n%,Loss\nMos to\nRecover,Penalty\nAmount,Penalty\n%,Excess\nLiquidation\nProceeds,Loan\nLiquidation\nReport,REO\nLiquidation\nReport,Split Loan Information\nReason,Split Loan Information\nDate\nSplit,Split Loan Information\nOrig Trustee\nLoan ID,Loan\nSpecial\nServicer,Workout\nStrategy,Orig\nTerm,Orig\nIO Per,UW\nMaturity Date,Mst Rcnt\nAppr Amt,Mst Rcnt\nAppr Dt,Normalized\nProp Type,SqFt/\nNoUnits,City,State
0,NaN,Metro Station,991072135,4850000,1.19,127.59,4059253,2015-02-01 00:00:00,-,-,-,2015-03-25 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,Resolved,120,0,2015-03-01 00:00:00,3800000,2011-08-15 00:00:00,RT-Shadow Anchor,45404,Orlando,FL
1,NaN,The Colony,991072127,5800000,3.46,50.5,4810571,2015-02-01 00:00:00,-,-,-,2015-03-02 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,11490000,2004-12-17 00:00:00,IN-Unclassified,72797,Culver City,CA
2,NaN,Riverwood Shopping Center,991072154,3880000,1.56,72.9,3253504,2015-02-01 00:00:00,-,-,-,2015-03-02 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,5325000,2004-11-23 00:00:00,RT-Shadow Anchor,87066,La Place,LA
3,NaN,The Lehman Mansion,991072093,8875000,1.2,68,6812218,2015-02-01 00:00:00,Fully defeased,-,-,2015-02-27 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,-,-,OF-Urban,13300,New York,NY
4,NaN,Woodland Park Apartments,991072097,8500000,1.2,78.7,7079006,2015-02-01 00:00:00,Fully defeased,-,-,2015-02-27 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,-,-,MF-Unclassified,152,Wisconsin Dells,WI

In [7]:
df = df.iloc[:,1:]
df.head()

,Property\nName,Trustee\nLoan ID,Secur\nLoan\nBalance,DSCR,LTV,Before Disposition\nBalance,Before Disposition\nPaid Thru\nDate,Before Disposition\nDefeased\nStatus,Before Disposition\nModified\nStatus,Before Disposition\nModification\nDate,Disposition\nDate,Disposition\nType,Disposition\nSub Type,Disposition\nComments,Loss\nAmount,Loss\n%,Loss\nMos to\nRecover,Penalty\nAmount,Penalty\n%,Excess\nLiquidation\nProceeds,Loan\nLiquidation\nReport,REO\nLiquidation\nReport,Split Loan Information\nReason,Split Loan Information\nDate\nSplit,Split Loan Information\nOrig Trustee\nLoan ID,Loan\nSpecial\nServicer,Workout\nStrategy,Orig\nTerm,Orig\nIO Per,UW\nMaturity Date,Mst Rcnt\nAppr Amt,Mst Rcnt\nAppr Dt,Normalized\nProp Type,SqFt/\nNoUnits,City,State
0,Metro Station,991072135,4850000,1.19,127.59,4059253,2015-02-01 00:00:00,-,-,-,2015-03-25 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,Resolved,120,0,2015-03-01 00:00:00,3800000,2011-08-15 00:00:00,RT-Shadow Anchor,45404,Orlando,FL
1,The Colony,991072127,5800000,3.46,50.5,4810571,2015-02-01 00:00:00,-,-,-,2015-03-02 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,11490000,2004-12-17 00:00:00,IN-Unclassified,72797,Culver City,CA
2,Riverwood Shopping Center,991072154,3880000,1.56,72.9,3253504,2015-02-01 00:00:00,-,-,-,2015-03-02 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,5325000,2004-11-23 00:00:00,RT-Shadow Anchor,87066,La Place,LA
3,The Lehman Mansion,991072093,8875000,1.2,68,6812218,2015-02-01 00:00:00,Fully defeased,-,-,2015-02-27 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,-,-,OF-Urban,13300,New York,NY
4,Woodland Park Apartments,991072097,8500000,1.2,78.7,7079006,2015-02-01 00:00:00,Fully defeased,-,-,2015-02-27 00:00:00,Paid at Maturity,-,-,-,-,-,-,-,-,-,-,-,-,-,C-III Asset Management LLC,No workout code,120,0,2015-03-01 00:00:00,-,-,MF-Unclassified,152,Wisconsin Dells,WI

In [8]:
print(range(df))

TypeError: 'DataFrame' object cannot be interpreted as an integer

In [9]:
print(df.range())

AttributeError: 'DataFrame' object has no attribute 'range'

In [26]:
print('Current shape:', df.shape)

Current shape: (5134, 36)

In [18]:
df = df.dropna(axis=0, thresh = 36)

In [19]:
print('Current shape:', df.shape)

Current shape: (5134, 36)

In [31]:
df1 = pd.read_excel('JPM Disposed.xlsx', skiprows = 1)

In [25]:
print('Current shape:', df1.shape)

Current shape: (0, 37)

In [24]:
df1 = df1.dropna(axis=0, thresh = 37)

In [27]:
print(df)

                         Property\nName Trustee\nLoan ID Secur\nLoan\nBalance  \
0                         Metro Station        991072135              4850000
1                            The Colony        991072127              5800000
2             Riverwood Shopping Center        991072154              3880000
3                    The Lehman Mansion        991072093              8875000
4              Woodland Park Apartments        991072097              8500000
...                                 ...              ...                  ...
5165     63-65 South Street - Hopkinton        940953050              4600000
5166          South Sierra Plaza Retail        940952799              6500000
5167                      Madison Plaza         30265122              2800000
5168                 Addison at Wyndham        170000064             30850000
5169  StratReal Industrial Portfolio II       30259617_1             37200000

      DSCR     LTV Before Disposition\nBalance  \
0     1.19  127.59                     4059253
1     3.46    50.5                     4810571
2     1.56    72.9                     3253504
3      1.2      68                     6812218
4      1.2    78.7                     7079006
...    ...     ...                         ...
5165  1.22    76.7                     4490104
5166  1.42    61.9                     6248662
5167  1.14      80                     2759367
5168  1.24    76.6                    30850000
5169  1.35    79.5                           -

     Before Disposition\nPaid Thru\nDate Before Disposition\nDefeased\nStatus  \
0                    2015-02-01 00:00:00                                    -
1                    2015-02-01 00:00:00                                    -
2                    2015-02-01 00:00:00                                    -
3                    2015-02-01 00:00:00                       Fully defeased
4                    2015-02-01 00:00:00                       Fully defeased
...                                  ...                                  ...
5165                 2010-04-01 00:00:00                                    -
5166                 2009-09-01 00:00:00                                    -
5167                 2009-05-01 00:00:00                                    -
5168                 2016-01-11 00:00:00                                    -
5169                                   -                                    -

     Before Disposition\nModified\nStatus  \
0                                       -
1                                       -
2                                       -
3                                       -
4                                       -
...                                   ...
5165                                    -
5166                                    -
5167                                    -
5168                                    -
5169                                    -

     Before Disposition\nModification\nDate    Disposition\nDate  \
0                                         -  2015-03-25 00:00:00
1                                         -  2015-03-02 00:00:00
2                                         -  2015-03-02 00:00:00
3                                         -  2015-02-27 00:00:00
4                                         -  2015-02-27 00:00:00
...                                     ...                  ...
5165                                      -  2011-04-07 00:00:00
5166                                      -  2010-07-08 00:00:00
5167                                      -  2010-07-01 00:00:00
5168                                      -  2016-03-11 00:00:00
5169                                      -                    -

        Disposition\nType Disposition\nSub Type Disposition\nComments  \
0        Paid at Maturity                     -                     -
1        Paid at Maturity                     -                     -
2        Paid at Maturity                     -                     -
3        Paid at Maturity                     -                     -
4        Paid at Maturity                     -                     -
...                   ...                   ...                   ...
5165                 Loss                     -                     -
5166                 Loss                     -                     -
5167                 Loss                     -                     -
5168  Under Investigation                     -                     -
5169  Under Investigation                     -                     -

     Loss\nAmount  Loss\n% Loss\nMos to\nRecover Penalty\nAmount Penalty\n%  \
0               -        -                     -               -          -
1               -        -                     -               -          -
2               -        -                     -               -          -
3               -        -                     -               -          -
4               -        -                     -               -          -
...           ...      ...                   ...             ...        ...
5165      1559404    33.73                    12               -          -
5166      2089055    32.14                    10               -          -
5167       943839    36.71                    14               -          -
5168            -        -                     -               -          -
5169            -        -                     -               -          -

     Excess\nLiquidation\nProceeds Loan\nLiquidation\nReport  \
0                                -                         -
1                                -                         -
2                                -                         -
3                                -                         -
4                                -                         -
...                            ...                       ...
5165                             -                         -
5166                             -                         -
5167                             -                         -
5168                             -                         -
5169                             -                         -

     REO\nLiquidation\nReport Split Loan Information\nReason  \
0                           -                              -
1                           -                              -
2                           -                              -
3                           -                              -
4                           -                              -
...                       ...                            ...
5165                        -                              -
5166                        -                              -
5167                        -                              -
5168                        -                              -
5169                        -                Prepay Restrict

     Split Loan Information\nDate\nSplit  \
0                                      -
1                                      -
2                                      -
3                                      -
4                                      -
...                                  ...
5165                                   -
5166                                   -
5167                                   -
5168                                   -
5169                                   -

     Split Loan Information\nOrig Trustee\nLoan ID  \
0                                                -
1                                                -
2                                                -
3                                                -
4                                                -
...                                            ...
5165                                             -
5166                                             -
5167                                             -
5168                                             -
5169                                      30259617

         Loan\nSpecial\nServicer Workout\nStrategy Orig\nTerm Orig\nIO Per  \
0     C-III Asset Management LLC          Resolved        120            0
1     C-III Asset Management LLC   No workout code        120            0
2     C-III Asset Management LLC   No workout code        120            0
3     C-III Asset Management LLC   No workout code        120            0
4     C-III Asset Management LLC   No workout code        120            0
...                          ...               ...        ...          ...
5165  C-III Asset Management LLC   No workout code        120           24
5166  C-III Asset Management LLC   No workout code        120            0
5167  C-III Asset Management LLC   No workout code        120           24
5168  C-III Asset Management LLC   No workout code        120          120
5169  C-III Asset Management LLC   No workout code        120          120

        UW\nMaturity Date Mst Rcnt\nAppr Amt    Mst Rcnt\nAppr Dt  \
0     2015-03-01 00:00:00            3800000  2011-08-15 00:00:00
1     2015-03-01 00:00:00           11490000  2004-12-17 00:00:00
2     2015-03-01 00:00:00            5325000  2004-11-23 00:00:00
3     2015-03-01 00:00:00                  -                    -
4     2015-03-01 00:00:00                  -                    -
...                   ...                ...                  ...
5165  2017-03-01 00:00:00                  -                    -
5166  2017-03-01 00:00:00                  -                    -
5167  2017-03-01 00:00:00                  -                    -
5168  2017-03-11 00:00:00                  -                    -
5169  2017-01-11 00:00:00                  -                    -

     Normalized\nProp Type SqFt/\nNoUnits             City  State
0         RT-Shadow Anchor          45404          Orlando     FL
1          IN-Unclassified          72797      Culver City     CA
2         RT-Shadow Anchor          87066         La Place     LA
3                 OF-Urban          13300         New York     NY
4          MF-Unclassified            152  Wisconsin Dells     WI
...                    ...            ...              ...    ...
5165           OF-Suburban          58584        Hopkinton     MA
5166         RT-Unanchored          25164          Fontana     CA
5167      RT-Shadow Anchor          17513  Madison Heights     MI
5168       MF-Unclassified            312       Glen Allen     VA
5169       IN-Unclassified        5003066          Various  Multi

[5134 rows x 36 columns]

In [28]:
print(df[130140,:])

TypeError: '(slice(130, 140, None), slice(None, None, None))' is an invalid key

In [45]:
print(df1[math.isnan(df1['Trustee\nLoan ID'])])

TypeError: cannot convert the series to <class 'float'>

In [42]:
math.isnan(df1['Trustee\nLoan ID'][130])

True

In [59]:
nan_df = pd.DataFrame()
i=0
for i in range(x-1):
    nan_df.append(math.isnan(df1['Trustee\nLoan ID'][i]))

TypeError: cannot concatenate object of type '<class 'bool'>'; only Series and DataFrame objs are valid

In [51]:
[x,y] = df1.shape
print(x)

5170